//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colorado.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Colorado.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default materials could not be loaded because the configuration file is not present..
        /// </summary>
        public static string Error_DefaultMaterialsFileDoesNotExist {
            get {
                return ResourceManager.GetString("Error_DefaultMaterialsFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default materials could not be loaded because the configuration file is not valid..
        /// </summary>
        public static string Error_DefaultMaterialsFileIsNotValid {
            get {
                return ResourceManager.GetString("Error_DefaultMaterialsFileIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Camera Down.
        /// </summary>
        public static string KeyCommand_MoveCameraDown_Description {
            get {
                return ResourceManager.GetString("KeyCommand_MoveCameraDown_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Camera Down.
        /// </summary>
        public static string KeyCommand_MoveCameraDown_Name {
            get {
                return ResourceManager.GetString("KeyCommand_MoveCameraDown_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Camera Left.
        /// </summary>
        public static string KeyCommand_MoveCameraLeft_Description {
            get {
                return ResourceManager.GetString("KeyCommand_MoveCameraLeft_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Camera Left.
        /// </summary>
        public static string KeyCommand_MoveCameraLeft_Name {
            get {
                return ResourceManager.GetString("KeyCommand_MoveCameraLeft_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Camera Right.
        /// </summary>
        public static string KeyCommand_MoveCameraRight_Description {
            get {
                return ResourceManager.GetString("KeyCommand_MoveCameraRight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Camera Right.
        /// </summary>
        public static string KeyCommand_MoveCameraRight_Name {
            get {
                return ResourceManager.GetString("KeyCommand_MoveCameraRight_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Camera Up.
        /// </summary>
        public static string KeyCommand_MoveCameraUp_Description {
            get {
                return ResourceManager.GetString("KeyCommand_MoveCameraUp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Camera Up.
        /// </summary>
        public static string KeyCommand_MoveCameraUp_Name {
            get {
                return ResourceManager.GetString("KeyCommand_MoveCameraUp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Camera Down.
        /// </summary>
        public static string KeyCommand_RotateAroundTargetDown_Description {
            get {
                return ResourceManager.GetString("KeyCommand_RotateAroundTargetDown_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Camera Down.
        /// </summary>
        public static string KeyCommand_RotateAroundTargetDown_Name {
            get {
                return ResourceManager.GetString("KeyCommand_RotateAroundTargetDown_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Camera Left.
        /// </summary>
        public static string KeyCommand_RotateAroundTargetLeft_Description {
            get {
                return ResourceManager.GetString("KeyCommand_RotateAroundTargetLeft_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Camera Left.
        /// </summary>
        public static string KeyCommand_RotateAroundTargetLeft_Name {
            get {
                return ResourceManager.GetString("KeyCommand_RotateAroundTargetLeft_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Camera Right.
        /// </summary>
        public static string KeyCommand_RotateAroundTargetRight_Description {
            get {
                return ResourceManager.GetString("KeyCommand_RotateAroundTargetRight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Camera Right.
        /// </summary>
        public static string KeyCommand_RotateAroundTargetRight_Name {
            get {
                return ResourceManager.GetString("KeyCommand_RotateAroundTargetRight_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Camera Up.
        /// </summary>
        public static string KeyCommand_RotateAroundTargetUp_Description {
            get {
                return ResourceManager.GetString("KeyCommand_RotateAroundTargetUp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Camera Up.
        /// </summary>
        public static string KeyCommand_RotateAroundTargetUp_Name {
            get {
                return ResourceManager.GetString("KeyCommand_RotateAroundTargetUp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale In.
        /// </summary>
        public static string KeyCommand_ScaleIn_Description {
            get {
                return ResourceManager.GetString("KeyCommand_ScaleIn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale In.
        /// </summary>
        public static string KeyCommand_ScaleIn_Name {
            get {
                return ResourceManager.GetString("KeyCommand_ScaleIn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Out.
        /// </summary>
        public static string KeyCommand_ScaleOut_Description {
            get {
                return ResourceManager.GetString("KeyCommand_ScaleOut_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Out.
        /// </summary>
        public static string KeyCommand_ScaleOut_Name {
            get {
                return ResourceManager.GetString("KeyCommand_ScaleOut_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom View.
        /// </summary>
        public static string KeyCommand_SetBottomCameraView_Description {
            get {
                return ResourceManager.GetString("KeyCommand_SetBottomCameraView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom View.
        /// </summary>
        public static string KeyCommand_SetBottomCameraView_Name {
            get {
                return ResourceManager.GetString("KeyCommand_SetBottomCameraView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front View.
        /// </summary>
        public static string KeyCommand_SetFrontCameraView_Description {
            get {
                return ResourceManager.GetString("KeyCommand_SetFrontCameraView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front View.
        /// </summary>
        public static string KeyCommand_SetFrontCameraView_Name {
            get {
                return ResourceManager.GetString("KeyCommand_SetFrontCameraView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isometric View.
        /// </summary>
        public static string KeyCommand_SetIsoCameraView_Description {
            get {
                return ResourceManager.GetString("KeyCommand_SetIsoCameraView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isometric View.
        /// </summary>
        public static string KeyCommand_SetIsoCameraView_Name {
            get {
                return ResourceManager.GetString("KeyCommand_SetIsoCameraView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left View.
        /// </summary>
        public static string KeyCommand_SetLeftCameraView_Description {
            get {
                return ResourceManager.GetString("KeyCommand_SetLeftCameraView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left View.
        /// </summary>
        public static string KeyCommand_SetLeftCameraView_Name {
            get {
                return ResourceManager.GetString("KeyCommand_SetLeftCameraView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rear View.
        /// </summary>
        public static string KeyCommand_SetRearCameraView_Description {
            get {
                return ResourceManager.GetString("KeyCommand_SetRearCameraView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rear View.
        /// </summary>
        public static string KeyCommand_SetRearCameraView_Name {
            get {
                return ResourceManager.GetString("KeyCommand_SetRearCameraView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right View.
        /// </summary>
        public static string KeyCommand_SetRightCameraView_Description {
            get {
                return ResourceManager.GetString("KeyCommand_SetRightCameraView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right View.
        /// </summary>
        public static string KeyCommand_SetRightCameraView_Name {
            get {
                return ResourceManager.GetString("KeyCommand_SetRightCameraView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top View.
        /// </summary>
        public static string KeyCommand_SetTopCameraView_Description {
            get {
                return ResourceManager.GetString("KeyCommand_SetTopCameraView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top View.
        /// </summary>
        public static string KeyCommand_SetTopCameraView_Name {
            get {
                return ResourceManager.GetString("KeyCommand_SetTopCameraView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Camera Mode.
        /// </summary>
        public static string KeyCommand_SwitchCameraMode_Description {
            get {
                return ResourceManager.GetString("KeyCommand_SwitchCameraMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Camera Mode.
        /// </summary>
        public static string KeyCommand_SwitchCameraMode_Name {
            get {
                return ResourceManager.GetString("KeyCommand_SwitchCameraMode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom To Fit.
        /// </summary>
        public static string KeyCommand_ZoomToFit_Description {
            get {
                return ResourceManager.GetString("KeyCommand_ZoomToFit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom To Fit.
        /// </summary>
        public static string KeyCommand_ZoomToFit_Name {
            get {
                return ResourceManager.GetString("KeyCommand_ZoomToFit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string UI_BlueColorTitle {
            get {
                return ResourceManager.GetString("UI_BlueColorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string UI_GreenColorTitle {
            get {
                return ResourceManager.GetString("UI_GreenColorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string UI_IntensityTitle {
            get {
                return ResourceManager.GetString("UI_IntensityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude:.
        /// </summary>
        public static string UI_Latitude {
            get {
                return ResourceManager.GetString("UI_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude:.
        /// </summary>
        public static string UI_Longitude {
            get {
                return ResourceManager.GetString("UI_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string UI_RedColorTitle {
            get {
                return ResourceManager.GetString("UI_RedColorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore default color settings.
        /// </summary>
        public static string UI_RestoreDefaultColorSettings {
            get {
                return ResourceManager.GetString("UI_RestoreDefaultColorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string UI_Time {
            get {
                return ResourceManager.GetString("UI_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorado 3D Viewer.
        /// </summary>
        public static string UI_Title {
            get {
                return ResourceManager.GetString("UI_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPS:.
        /// </summary>
        public static string Viewer_FPSLabel {
            get {
                return ResourceManager.GetString("Viewer_FPSLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorado 3D Viewer.
        /// </summary>
        public static string Viewer_Title {
            get {
                return ResourceManager.GetString("Viewer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangles Count:.
        /// </summary>
        public static string Viewer_TrianglesCountLabel {
            get {
                return ResourceManager.GetString("Viewer_TrianglesCountLabel", resourceCulture);
            }
        }
    }
}
